### ISSUE TITLE
RS485 Support

### ISSUE THREAD

**Issue by Speedy2k** [MyrikLD/pyc45b#1]
Hi MyrikLD, i would like to know if it would be possoble to add RS485 chip45 bootloader support to your python script ? you can contact me for any info.
martin@erablitek.com

**Comment by MyrikLD** [comment]
Hello Speedy2k.
Yes it is possible. But while working with the boot loader I found a serious error , because of which I had to go to xboot bootloader.

**Comment by Speedy2k** [comment]
Ok, can you develop a little bit on that error? We have ported the chip45 on the attiny because we needed to remotelly update our firmware over a rs485 network. If this problem is still there and we haven't happend to face it, it will be a good thing to solve it!

Also what would be your price for an update with rs485 support to your script?

Envoyé de mon iPhone

**Comment by MyrikLD** [comment]
Added
